<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robin_simulation</name>
  <version>0.0.0</version>
  <description>ROBIN welding process simulation package</description>
  <maintainer email="daniel.haas@3d-components.co">Daniel Haas</maintainer>
  <maintainer email="virgilio.gomez@3d-components.co">Virgilio Gomez</maintainer>
  <maintainer email="jayant@mil-as.no">Jayant Singh</maintainer>
  <license>AGPL-3.0-only</license>

  <exec_depend>ur_simulation_gz</exec_depend>
  <exec_depend>robin_bringup</exec_depend>
  <exec_depend>robin_hardware_ur</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robin_interfaces</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
