#!/usr/bin/env python3
"""Update README coverage badge from coverage.xml.

Looks for or inserts a Shields.io coverage badge like:
[![Coverage](https://img.shields.io/badge/coverage-85%25-green.svg)](#)

Workflow:
- Expect coverage.xml at repo root (generated by pytest --cov-report=xml)
- Parse coverage percent
- Update existing badge or insert under the other badges near the top
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
import subprocess
import shutil
import time
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
COV_XML = ROOT / 'coverage.xml'
README = ROOT / 'README.md'


def load_coverage_percent() -> int | None:
    if not COV_XML.exists():
        return None
    try:
        tree = ET.parse(COV_XML)
        root = tree.getroot()
        # coverage.py writes attributes on root element
        # Try lines-covered / lines-valid first
        covered = root.attrib.get('lines-covered')
        valid = root.attrib.get('lines-valid')
        if covered and valid:
            c = int(covered)
            v = int(valid) or 1
            return int(round((c / v) * 100))
        # Fallback to line-rate (0..1)
        line_rate = root.attrib.get('line-rate')
        if line_rate is not None:
            rate = float(line_rate)
            return int(round(rate * 100))
    except Exception:
        return None
    return None


def _newest_coverage_data_mtime() -> float:
    """Return latest mtime among coverage data artifacts.

    Checks .coverage[.*] files and htmlcov/index.html if present, and returns
    the newest modification time found. Returns 0.0 if none exist.
    """
    candidates: list[Path] = []
    candidates.append(ROOT / '.coverage')
    candidates.extend(ROOT.glob('.coverage.*'))
    candidates.append(ROOT / 'htmlcov' / 'index.html')
    mtimes: list[float] = []
    for p in candidates:
        try:
            if p.exists():
                mtimes.append(p.stat().st_mtime)
        except OSError:
            continue
    return max(mtimes) if mtimes else 0.0


def ensure_fresh_xml() -> None:
    """Regenerate coverage.xml if missing or stale versus coverage data.

    Uses the `coverage` CLI if available. If regeneration fails, silently keep
    the existing file so the script can still parse it (even if stale).
    """
    data_mtime = _newest_coverage_data_mtime()
    xml_mtime = COV_XML.stat().st_mtime if COV_XML.exists() else 0.0
    if data_mtime and data_mtime > xml_mtime:
        cov_exe = shutil.which('coverage')
        if cov_exe:
            try:
                # Regenerate XML in place
                subprocess.run(
                    [cov_exe, 'xml', f'-o={COV_XML}'],
                    cwd=str(ROOT),
                    check=False,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                # Give the FS a moment to flush mtime changes on some filesystems
                time.sleep(0.1)
            except Exception:
                # Best-effort: ignore and proceed with existing XML (if any)
                pass


def color_for(pct: int) -> str:
    if pct >= 90:
        return 'brightgreen'
    if pct >= 80:
        return 'green'
    if pct >= 70:
        return 'yellow'
    if pct >= 50:
        return 'orange'
    return 'red'


def update_readme_badge(pct: int) -> bool:
    if not README.exists():
        return False
    text = README.read_text(encoding='utf-8')
    badge_re = re.compile(
        r'\[!\[Coverage\]\(https://img\.shields\.io/badge/coverage-[0-9]+%25-[a-zA-Z]+\.svg\)\]',
        re.I,
    )
    new_badge = f'[![Coverage](https://img.shields.io/badge/coverage-{pct}%25-{color_for(pct)}.svg)](#)'

    if badge_re.search(text):
        updated = badge_re.sub(new_badge, text)
        if updated != text:
            README.write_text(updated, encoding='utf-8')
            return True
        return False

    # Insert after last shields.io badge near the top (first 30 lines)
    lines = text.splitlines()
    insert_at = None
    for i, line in enumerate(lines[:30]):
        if 'img.shields.io' in line:
            insert_at = i
    if insert_at is None:
        # No badges found; insert after title line if present
        if lines and lines[0].startswith('# '):
            insert_at = 0
        else:
            insert_at = -1

    if insert_at >= 0:
        lines.insert(insert_at + 1, new_badge)
        README.write_text('\n'.join(lines) + '\n', encoding='utf-8')
        return True
    else:
        # Prepend
        README.write_text(new_badge + '\n' + text, encoding='utf-8')
        return True


def main() -> int:
    # Try to ensure coverage.xml is current before parsing
    ensure_fresh_xml()
    pct = load_coverage_percent()
    if pct is None:
        # Skip quietly if coverage.xml not present
        print('coverage.xml not found; skipping coverage badge update')
        return 0
    changed = update_readme_badge(pct)
    if changed:
        print(f'Updated coverage badge to {pct}%')
    else:
        print('Coverage badge already up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
